Assembly-specific code moved into wdl
oicr-gsi/smmipsWorkflow pull request #9
Opened 2023-06-30 20:08 UTC by hannahdriver

Moving assembly-specific code into the workflow

2023-07-04 16:21 UTC, bibilujan approved these changes
Looks good!

2023-07-04 16:21 UTC, bibilujan commented on smmipsQC.wdl
> +      refDict = resources[reference].refDict,
you probably don't need this last comma

2023-07-04 23:17 UTC, pruzanov requested changes
Please update the CHANGELOG file too

2023-07-06 14:06 UTC, pruzanov approved these changes

2023-07-06 15:58 UTC, merged